service: dynamodb-crud-api-leads

provider: 
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.leadsTableName}

custom:
  leadsTableName: leads-table-${self:provider.stage}

plugin:
  - serverless-iam-roles-per-function

getAllLeads:
    handler: api.getAllLeads
    name: get-all-leads
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: leads
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:Scan"
        Resource: !GetAtt LeadsTable.Arn

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.leadsTableName}
        AttributeDefinitions:
          - AttributeName: leadId
            AttributeType: S
          - AttributeName: name
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: type
            AttributeType: S
          - AttributeName: phone
            AttributeType: S
          - AttributeName: prospectAt
            AttributeType: S
          - AttributeName: clientAt
            AttributeType: S
        KeySchema:
          - AttributeName: leadId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
