name: 'Deploy API WITH CRUD API'

on:
  push:
    branches: [ main ]

jobs:
  deploy:
  
  runs-on: ubuntu-latest

  steps:

  - uses: actions/checkout@v2
  - uses: actions/cache/v2
    with:
      path: '**/node_modules'
      key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock')}}

  - name: Use Node.js 14.x
    uses: actions/setup-node@v1
    with:
      node-version: 14.x
  - name: Install Dependencies
    run: yarn install

  - name: serverless deploy
    uses: serverless/gihub-action@master
    with:
      args: deploy
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
